#!/bin/sh


while true; do

    # Sink.
    default_sink=$(pactl get-default-sink)
    default_muted=$(pactl get-sink-mute $default_sink)
    default_volume=$(pactl get-sink-volume $default_sink | awk '{print $5}')
    default_name=$(pulsemixer --list-sinks | grep Default | cut -d ',' -f 2 | awk '{print $2}')
    sink="$default_name: [$default_muted], [$default_volume]"

    # Battery.
    battery="$(upower -b | grep percentage | awk '{print $2}')"
    if [ -n "$battery" ]; then
        battery="battery: $battery"
    fi

    # Date and time.
    date="$(date +'%a %b %d %H:%M:%S')"

    # Network.
    network=
    for ndev in $(ip -br a | tail +2 | awk '{print $1}'); do
        ndev_data="$(nmcli | grep $ndev | head -1)"
        if [ -z "$network" ]; then
            network="$ndev_data"
        else
            network="$network $DELIMITER $ndev_data"
        fi
    done

    # Format the bar.
    bar=""
    for mod in "$sink" "$network" "$battery" "$date"; do
        if [ -n "$mod" ]; then
            # Prevent an extra whitespace at the
            # beginning of the bar.
            if [ -n "$bar" ]; then
                bar="$bar | $mod"
            else
                bar="$mod"
            fi
        fi
    done

    echo "$bar"

    sleep 1
done
