#!/bin/sh

while true; do
    # Sink
    # default_sink=$(pactl get-default-sink)
    # default_muted=$(pactl get-sink-mute $default_sink)
    # default_volume=$(pactl get-sink-volume $default_sink | awk '{print $5}')
    # sink="sink: [$default_muted], [$default_volume]"

    # Battery
    battery="$(upower -b | grep percentage | awk '{print $2}')"
    if ! [ -z "$battery" ]; then
        battery="| battery: $battery"
    fi

    # Date and time
    date="| $(date +'%a %b %d %H:%M:%S')"

    # Network
    network=
    for ndev in $(ip -br a | tail +2 | awk '{print $1}'); do
        network="$network | $(nmcli | grep $ndev | head -1)"
    done

    echo "$network $date $battery"

    sleep 1
done
